// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CATRFunction wrapper class

class CATRFunction : public COleDispatchDriver
{
public:
	CATRFunction() {}		// Calls COleDispatchDriver default constructor
	CATRFunction(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CATRFunction(const CATRFunction& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	BOOL GetIncludeNulls();
	void SetIncludeNulls(BOOL bNewValue);
};
