// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CAutomaticText wrapper class

class CAutomaticText : public COleDispatchDriver
{
public:
	CAutomaticText() {}		// Calls COleDispatchDriver default constructor
	CAutomaticText(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CAutomaticText(const CAutomaticText& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	BOOL GetHide();
	void SetHide(BOOL bNewValue);
	BOOL GetMove();
	void SetMove(BOOL bNewValue);
	BOOL GetResize();
	void SetResize(BOOL bNewValue);
	BOOL GetRotate();
	void SetRotate(BOOL bNewValue);
	BOOL GetTrim();
	void SetTrim(BOOL bNewValue);
	BOOL GetWrap();
	void SetWrap(BOOL bNewValue);
};
