#if !defined(AFX_CHARTGRIDNAVIGATOR_H__277A27BB_3B7C_461B_981D_F0E00547F8A9__INCLUDED_)
#define AFX_CHARTGRIDNAVIGATOR_H__277A27BB_3B7C_461B_981D_F0E00547F8A9__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CChartGridNavigator wrapper class

class CChartGridNavigator : public CWnd
{
protected:
	DECLARE_DYNCREATE(CChartGridNavigator)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xece333f, 0xc18e, 0x49a9, { 0xbe, 0x39, 0x82, 0xa9, 0x34, 0x2a, 0x83, 0xbb } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void SetGrid(LPDISPATCH newValue);
	void SetGridLink(long nNewValue);
	void EnableButtons();
	unsigned long GetColor();
	void SetColor(unsigned long newValue);
	void SetGridLinkx64(const VARIANT& newValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CHARTGRIDNAVIGATOR_H__277A27BB_3B7C_461B_981D_F0E00547F8A9__INCLUDED_)
