// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CPointer;
class CHierarchicalClustering;
class CKMeansClustering;
class CQTClustering;

/////////////////////////////////////////////////////////////////////////////
// CClusteringTool wrapper class

class CClusteringTool : public COleDispatchDriver
{
public:
	CClusteringTool() {}		// Calls COleDispatchDriver default constructor
	CClusteringTool(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CClusteringTool(const CClusteringTool& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	VARIANT GetSeries();
	void SetSeries(const VARIANT& newValue);
	BOOL GetColorEach();
	void SetColorEach(BOOL bNewValue);
	long GetDistance();
	void SetDistance(long nNewValue);
	long GetLinkage();
	void SetLinkage(long nNewValue);
	long GetMethod();
	void SetMethod(long nNewValue);
	CPointer GetCenters();
	CPointer GetCentroids();
	BOOL GetShowBounds();
	void SetShowBounds(BOOL bNewValue);
	long GetTransparency();
	void SetTransparency(long nNewValue);
	CHierarchicalClustering GetHierarchical();
	CKMeansClustering GetKMeans();
	CQTClustering GetQTClustering();
	double GetMinkowskiLambda();
	void SetMinkowskiLambda(double newValue);
};
