// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CGaugeHand;

/////////////////////////////////////////////////////////////////////////////
// CGaugeHandItem wrapper class

class CGaugeHandItem : public COleDispatchDriver
{
public:
	CGaugeHandItem() {}		// Calls COleDispatchDriver default constructor
	CGaugeHandItem(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CGaugeHandItem(const CGaugeHandItem& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CGaugeHand GetFormat();
	double GetValue();
	void SetValue(double newValue);
};
