// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CGaugeHandItem;

/////////////////////////////////////////////////////////////////////////////
// CGaugeHands wrapper class

class CGaugeHands : public COleDispatchDriver
{
public:
	CGaugeHands() {}		// Calls COleDispatchDriver default constructor
	CGaugeHands(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CGaugeHands(const CGaugeHands& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CGaugeHandItem GetItems(long AIndex);
	long Add(double AValue);
};
