// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "gradientcolors.h"

// Dispatch interfaces referenced by this interface
#include "gradientcolor.h"


/////////////////////////////////////////////////////////////////////////////
// CGradientColors properties

/////////////////////////////////////////////////////////////////////////////
// CGradientColors operations

void CGradientColors::Clear()
{
	InvokeHelper(0xc9, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

CGradientColor CGradientColors::GetItems(long Index)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xca, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, parms,
		Index);
	return CGradientColor(pDispatch);
}

long CGradientColors::AddColor(double AOffset, unsigned long AColor, long ATransparency)
{
	long result;
	static BYTE parms[] =
		VTS_R8 VTS_I4 VTS_I4;
	InvokeHelper(0xcb, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		AOffset, AColor, ATransparency);
	return result;
}

void CGradientColors::Delete(long Index)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xcc, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Index);
}
