// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CGradientColor;

/////////////////////////////////////////////////////////////////////////////
// CGradientColors wrapper class

class CGradientColors : public COleDispatchDriver
{
public:
	CGradientColors() {}		// Calls COleDispatchDriver default constructor
	CGradientColors(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CGradientColors(const CGradientColors& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	void Clear();
	CGradientColor GetItems(long Index);
	long AddColor(double AOffset, unsigned long AColor, long ATransparency);
	void Delete(long Index);
};
