// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CKMeansClustering wrapper class

class CKMeansClustering : public COleDispatchDriver
{
public:
	CKMeansClustering() {}		// Calls COleDispatchDriver default constructor
	CKMeansClustering(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CKMeansClustering(const CKMeansClustering& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetLinkage();
	void SetLinkage(long nNewValue);
	long GetNumClusters();
	void SetNumClusters(long nNewValue);
	long GetMaxIterations();
	void SetMaxIterations(long nNewValue);
};
