// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CParetoFunction wrapper class

class CParetoFunction : public COleDispatchDriver
{
public:
	CParetoFunction() {}		// Calls COleDispatchDriver default constructor
	CParetoFunction(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CParetoFunction(const CParetoFunction& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
};
