// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CPieAngle wrapper class

class CPieAngle : public COleDispatchDriver
{
public:
	CPieAngle() {}		// Calls COleDispatchDriver default constructor
	CPieAngle(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CPieAngle(const CPieAngle& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	double GetStartAngle();
	void SetStartAngle(double newValue);
	double GetMidAngle();
	void SetMidAngle(double newValue);
	double GetEndAngle();
	void SetEndAngle(double newValue);
};
