// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "rvifunction.h"

// Dispatch interfaces referenced by this interface
#include "pen.h"
#include "series.h"


/////////////////////////////////////////////////////////////////////////////
// CRVIFunction properties

/////////////////////////////////////////////////////////////////////////////
// CRVIFunction operations

CPen1 CRVIFunction::GetSignalPen()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0xc9, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CPen1(pDispatch);
}

CSeries CRVIFunction::GetSignal()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0xca, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CSeries(pDispatch);
}
