// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CShapeCallout wrapper class

class CShapeCallout : public COleDispatchDriver
{
public:
	CShapeCallout() {}		// Calls COleDispatchDriver default constructor
	CShapeCallout(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CShapeCallout(const CShapeCallout& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetPointPosition();
	void SetPointPosition(long nNewValue);
	long GetPosition();
	void SetPosition(long nNewValue);
	long GetSide();
	void SetSide(long nNewValue);
	long GetSize();
	void SetSize(long nNewValue);
	long GetWidth();
	void SetWidth(long nNewValue);
};
