// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CSobelFilter wrapper class

class CSobelFilter : public COleDispatchDriver
{
public:
	CSobelFilter() {}		// Calls COleDispatchDriver default constructor
	CSobelFilter(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CSobelFilter(const CSobelFilter& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
};
