// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "subcharttool.h"

// Dispatch interfaces referenced by this interface
#include "chartcollection.h"


/////////////////////////////////////////////////////////////////////////////
// CSubChartTool properties

/////////////////////////////////////////////////////////////////////////////
// CSubChartTool operations

CChartCollection CSubChartTool::GetCharts()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0xc9, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CChartCollection(pDispatch);
}

short CSubChartTool::GetCursor()
{
	short result;
	InvokeHelper(0xca, DISPATCH_PROPERTYGET, VT_I2, (void*)&result, NULL);
	return result;
}

void CSubChartTool::SetCursor(short nNewValue)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0xca, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}
