#if !defined(AFX_TEEEDITOR_H__BB1B062B_37FE_4F9E_9F75_5C53309D75DC__INCLUDED_)
#define AFX_TEEEDITOR_H__BB1B062B_37FE_4F9E_9F75_5C53309D75DC__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CTeeEditorShowPages;
class CTeeEditorOptions;

/////////////////////////////////////////////////////////////////////////////
// CTeeEditor wrapper class

class CTeeEditor : public CWnd
{
protected:
	DECLARE_DYNCREATE(CTeeEditor)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xcea04253, 0xec73, 0x49fa, { 0xba, 0x73, 0x44, 0x9c, 0x23, 0x77, 0xff, 0x54 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void SetChart(LPDISPATCH newValue);
	void SetChartLink(long nNewValue);
	void AboutBox();
	void SetChartLinkx64(const VARIANT& newValue);
	CString GetEditorTitle();
	void SetEditorTitle(LPCTSTR lpszNewValue);
	long GetDefaultPage();
	void SetDefaultPage(long nNewValue);
	void ShowEditor();
	BOOL GetAutoRepaint();
	void SetAutoRepaint(BOOL bNewValue);
	CTeeEditorShowPages GetShowPages();
	long GetEditorLink();
	CTeeEditorOptions GetOptions();
	BOOL GetTreeView();
	void SetTreeView(BOOL bNewValue);
	BOOL GetHighLightTabs();
	void SetHighLightTabs(BOOL bNewValue);
	long GetPixelsPerInch();
	void SetPixelsPerInch(long nNewValue);
	BOOL GetRememberPosition();
	void SetRememberPosition(BOOL bNewValue);
	long GetGalleryHeight();
	void SetGalleryHeight(long nNewValue);
	long GetGalleryWidth();
	void SetGalleryWidth(long nNewValue);
	long GetHeight();
	void SetHeight(long nNewValue);
	long GetWidth();
	void SetWidth(long nNewValue);
	VARIANT GetEditorLinkx64();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TEEEDITOR_H__BB1B062B_37FE_4F9E_9F75_5C53309D75DC__INCLUDED_)
