#if !defined(AFX_TEEPREVIEWER_H__2FD03F4F_1B97_45EE_A595_1AC6F6E813DB__INCLUDED_)
#define AFX_TEEPREVIEWER_H__2FD03F4F_1B97_45EE_A595_1AC6F6E813DB__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CTeePreviewerOptions;

/////////////////////////////////////////////////////////////////////////////
// CTeePreviewer wrapper class

class CTeePreviewer : public CWnd
{
protected:
	DECLARE_DYNCREATE(CTeePreviewer)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x43c0daf8, 0xb613, 0x4027, { 0x94, 0xa6, 0x6f, 0x97, 0xf2, 0x47, 0x25, 0x40 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void SetChart(LPDISPATCH newValue);
	void SetChartLink(long nNewValue);
	void AboutBox();
	void SetChartLinkx64(const VARIANT& newValue);
	CString GetPreviewTitle();
	void SetPreviewTitle(LPCTSTR lpszNewValue);
	void ShowPreview();
	unsigned long GetPaperColor();
	void SetPaperColor(unsigned long newValue);
	long GetPreviewerLink();
	BOOL GetMaximized();
	void SetMaximized(BOOL bNewValue);
	CTeePreviewerOptions GetOptions();
	VARIANT GetPreviewerLinkx64();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TEEPREVIEWER_H__2FD03F4F_1B97_45EE_A595_1AC6F6E813DB__INCLUDED_)
