// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "teeshapeitem.h"

// Dispatch interfaces referenced by this interface
#include "teecustomshape.h"


/////////////////////////////////////////////////////////////////////////////
// CTeeShapeItem properties

/////////////////////////////////////////////////////////////////////////////
// CTeeShapeItem operations

CTeeCustomShape CTeeShapeItem::GetShape()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0xc9, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CTeeCustomShape(pDispatch);
}
