// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "teeshapes.h"

// Dispatch interfaces referenced by this interface
#include "teeshapeitem.h"


/////////////////////////////////////////////////////////////////////////////
// CTeeShapes properties

/////////////////////////////////////////////////////////////////////////////
// CTeeShapes operations

long CTeeShapes::Add()
{
	long result;
	InvokeHelper(0xc9, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

CTeeShapeItem CTeeShapes::GetItem(long AIndex)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xca, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, parms,
		AIndex);
	return CTeeShapeItem(pDispatch);
}
