// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CTeeAnimation;
class CAxis;

/////////////////////////////////////////////////////////////////////////////
// CTransformAnimation wrapper class

class CTransformAnimation : public COleDispatchDriver
{
public:
	CTransformAnimation() {}		// Calls COleDispatchDriver default constructor
	CTransformAnimation(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CTransformAnimation(const CTransformAnimation& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetDuration();
	void SetDuration(long nNewValue);
	BOOL GetEnabled();
	void SetEnabled(BOOL bNewValue);
	BOOL GetInverted();
	void SetInverted(BOOL bNewValue);
	BOOL GetLoop();
	void SetLoop(BOOL bNewValue);
	CTeeAnimation GetParent();
	long GetStartTime();
	void SetStartTime(long nNewValue);
	long GetTiming();
	void SetTiming(long nNewValue);
	long GetTimingStyle();
	void SetTimingStyle(long nNewValue);
	CString GetTitle();
	void SetTitle(LPCTSTR lpszNewValue);
	BOOL GetTwoWay();
	void SetTwoWay(BOOL bNewValue);
	long GetSeries();
	void SetSeries(long nNewValue);
	CAxis GetAxis();
	BOOL GetClip();
	void SetClip(BOOL bNewValue);
	long GetFade();
	void SetFade(long nNewValue);
	long GetMaxZoom();
	void SetMaxZoom(long nNewValue);
	long GetRotateMin();
	void SetRotateMin(long nNewValue);
	long GetRotateMax();
	void SetRotateMax(long nNewValue);
	long GetScale();
	void SetScale(long nNewValue);
	long GetTranslateStyle();
	void SetTranslateStyle(long nNewValue);
	long GetTarget();
	void SetTarget(long nNewValue);
	BOOL GetUseBounds();
	void SetUseBounds(BOOL bNewValue);
	long GetZoomStyle();
	void SetZoomStyle(long nNewValue);
};
