// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CWorldFlags wrapper class

class CWorldFlags : public COleDispatchDriver
{
public:
	CWorldFlags() {}		// Calls COleDispatchDriver default constructor
	CWorldFlags(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CWorldFlags(const CWorldFlags& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	BOOL GetVisible();
	void SetVisible(BOOL bNewValue);
};
